export PATH_TO_EMSCRIPTEN="emcc"
export PATH_TO_NIMBASE="/Users/adam/.asdf/installs/nimskull/0.1.0-dev.21252/lib/nimbase.h"
export PATH_TO_NIM="nim"
# export PATH_TO_NIM="/Users/adam/.nimble/bin/nim"
export PATH_TO_C_NATIVE="gcc"
